### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by booshtukka** [K1LL3R234/homebridge-texecom#7]
**Describe the bug**
I've tried to install this via HomeBridge UI but it failed. I'm sure I could mess with the server until it works, but thought you would prefer to try to get it install out of the box, like other plugins do. :)

**To Reproduce**
1. In HomeBridge UI, search for "homebridge-texecom-full" and choose install

**Expected behavior**
I expected it to install automatically

**Details**
These are the errors I received:

DIR: /usr/local
CMD: npm install -g homebridge-texecom-full@4.2.2-beta1

> @serialport/bindings@8.0.8 install
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - executable path is ""
gyp ERR! find Python - "" could not be run
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - executable path is ""
gyp ERR! find Python - "" could not be run
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:306:11)
gyp ERR! stack at PythonFinder.findPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:164:17)
gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
gyp ERR! stack at async configure (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:27:18)
gyp ERR! stack at async run (/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Darwin 23.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-texecom-full/node_modules/@serialport/bindings
gyp ERR! node -v v20.15.0
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok 
npm error code 1
npm error path /usr/local/lib/node_modules/homebridge-texecom-full/node_modules/@serialport/bindings
npm error command failed
npm error command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

npm error A complete log of this run can be found in: /Users/ak/.npm/_logs/2024-10-08T18_36_40_487Z-debug-0.log

Error: Operation failed with code 1.
You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

**Comment by K1LL3R234** [comment]
Hi there thank you for letting me know I will have a look and fix it ASAP. Thanks for letting me know!

**Comment by booshtukka** [comment]
Thank you! Excited to try this :)Sent from my iPhoneOn 8 Oct 2024, at 20:26, Chris Posthumus ***@***.***> wrote:﻿
Hi there thank you for letting me know I will have a look and fix it ASAP. Thanks for letting me know!

**Comment by K1LL3R234** [comment]
What hardware are you using? And what version of homebridge?

**Comment by K1LL3R234** [comment]
Try Beta2 and let me know.

**Comment by booshtukka** [comment]
HB is running on a Mac Mini. HB is very 1.8.4. 

Still the same problem, unfortunately. :(

USER: ak
DIR: /usr/local
CMD: npm install -g homebridge-texecom-full@4.2.3


> @serialport/bindings@8.0.8 install
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - executable path is ""
gyp ERR! find Python - "" could not be run
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - executable path is ""
gyp ERR! find Python - "" could not be run
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:306:11)
gyp ERR! stack at PythonFinder.findPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:164:17)
gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
gyp ERR! stack at async configure (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:27:18)
gyp ERR! stack at async run (/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Darwin 23.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-texecom-full/node_modules/@serialport/bindings
gyp ERR! node -v v20.15.0
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok 
npm error code 1
npm error path /usr/local/lib/node_modules/homebridge-texecom-full/node_modules/@serialport/bindings
npm error command failed
npm error command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

npm error A complete log of this run can be found in: /Users/ak/.npm/_logs/2024-10-09T10_16_25_563Z-debug-0.log

Error: Operation failed with code 1.
You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

**Comment by K1LL3R234** [comment]
Can you install python. with this command in terminal ```$ brew install python3```
